# {{@@ header() @@}}
# os: {{@@ os @@}}

{%@@ if os == "darwin" @@%}
eval "$(/opt/homebrew/bin/brew shellenv)"
{%@@ endif @@%}
# Prepend user bins; uniqueness is enforced by .zshenv (typeset -U PATH path)
path=("$HOME/.local/bin" "$HOME/bin" $path)
