# Set the history file path
HISTFILE=$HOME/.zsh_history
# Set history save size and total history size
SAVEHIST=10000
HISTSIZE=10000
HISTORY_IGNORE="pwd:ls:clear"

# Set shell options for history behavior
setopt BANG_HIST
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
# Write the history file in the ':start:elapsed;command' format.
setopt EXTENDED_HISTORY

setopt PROMPT_SUBST

# Disallow `>` to overwrite existing files. Use `>|`(sh compatible) or `>!`(zsh only) instead.
setopt NO_CLOBBER

# Allow comments starting with `#` in the interactive shell.
setopt INTERACTIVE_COMMENTS
# the cursor is moved to the end of the word if either a single match is inserted or menu completion is performed.
setopt alwaystoend

# Perform cd to a directory if the typed command is invalid, but is a directory.
setopt autocd
# useful for pushd, pushd +N, popd, cd -N, dirs -v
setopt autopushd
setopt pushdignoredups
setopt pushdsilent
# `PUSHDMINUS` swapped the meaning of `cd +1` and `cd -1`, in favor of `cd -N` for choosing N+1 th item from the top.
setopt pushdminus

setopt longlistjobs

# Ensures that Unicode combining characters are handled properly in Zsh
setopt combiningchars
# Allow completion in the middle of a word
setopt completeinword
# Disable XON/XOFF which is useless nowadays
# same as stty -ixon ?
setopt noflowcontrol

# ZSH uses this to determine how long to wait (in hundredths of a second) for additional characters in sequence. Default is 0.4 seconds.
# 1=10ms for key sequences
KEYTIMEOUT=1

#
# DOTFILES
#
if [ -f "$HOME/dotfiles/config.yaml" ]; then
    export DOTDROP_CONFIG="$HOME/dotfiles/config.yaml"
elif [ -f "$HOME/projects/dotfiles/config.yaml" ]; then
    export DOTDROP_CONFIG="$HOME/projects/dotfiles/config.yaml"
fi

#
# Vim Mode
#
bindkey -v
export EDITOR=nvim
export SYSTEMD_EDITOR=nvim

# change cursor
_fix_cursor() {
    local _key=${1:-$KEYMAP}
    local _shape=0
    case ${_key} in
        vicmd|visual) _shape=1 ;; # block
        viins|main|command|isearch) _shape=5 ;; # beam
        viopp) _shape=0 ;; # block
        *) _shape=0 ;; # block
    esac
    printf $'\e[%d q' "${_shape}"
}
zle-keymap-select () {
    _fix_cursor $KEYMAP
}
zle -N zle-keymap-select
zle-line-init() {
    _fix_cursor $KEYMAP
}
zle -N zle-line-init
zle-line-finish() {
    _fix_cursor vicmd
}
zle -N zle-line-finish

#
# Theme
#
# if use ohmyzsh vi mode then this need to be placed after it to enable transient prompt
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
    eval "$(oh-my-posh init zsh --config ${HOME}/.config/oh-my-posh/custom.omp.toml)"
fi

#
# PLUGINS
#

# ohmyzsh vi mode
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=false
VI_MODE_SET_CURSOR=true
MODE_INDICATOR=""
INSERT_MODE_INDICATOR=""
VI_MODE_CURSOR_NORMAL=1
VI_MODE_CURSOR_VISUAL=1
VI_MODE_CURSOR_INSERT=5
VI_MODE_CURSOR_OPPEND=0

# zsh-autosuggestions
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# zsh-syntax-highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS+=(main brackets pattern)
typeset -A ZSH_HIGHLIGHT_PATTERNS
# To have commands starting with `rm -rf` highlighted:
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=yellow,bold,underline')

# fd
# see also fd ignore file in ~/.config/fd/ignore
alias fd='fd --hidden --exclude .git' #-p

# fzf
# fzf, use fd instead of find (fd reads ~/.fdignore)
local _fzf_preview_argument="if [ -d {} ]; \
  then eza -a --tree -L1 --color=always --icons=always {} | head -n 200; \
  else bat --color=always --line-range=:500 {}; \
  fi"
export FZF_DEFAULT_COMMAND="fd -H -E .git --type d --type f"
# Ctrl + T command
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
# Alt + C command 
export FZF_ALT_C_COMMAND="fd -H -E .git --type d"
export FZF_CTRL_T_OPTS="--bind 'ctrl-/:toggle-preview' ${FZF_CTRL_T_OPTS:-} --preview '${_fzf_preview_argument}' --preview-window wrap"
export FZF_ALT_C_OPTS="--bind 'ctrl-/:toggle-preview' ${FZF_ALT_C_OPTS:-} --preview '${_fzf_preview_argument}' --preview-window wrap"
# allow color from fd
export FZF_DEFAULT_OPTS="--ansi"
# "**" command syntax
_fzf_compgen_path() {
    fd -H -E .git --type d --type f . "$1"
}
# "**" command syntax (for directories only)
_fzf_compgen_dir() {
    fd -H -E .git --type d . "$1"
}
_fzf_comprun() {
    local command=$1
    shift

    case "$command" in
        export|unset) fzf --preview "eval 'echo \$'{}" "$@" ;;
        ssh) fzf --preview "dig {}" "$@" ;;
        *) fzf --preview "${_fzf_preview_argument}" --preview-window wrap "$@" ;;
    esac
}
alias fzfp="fzf --preview '${_fzf_preview_argument}' --preview-window wrap"

source <(fzf --zsh)

# zimfw
ZSH_PLUGIN_DIR=~/.zsh-plugins
ZIM_HOME=$ZSH_PLUGIN_DIR
ZIM_CONFIG_FILE=~/.config/zsh/.zimrc

zstyle ':zim:zmodule' use 'degit'

# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
    curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

# Install missing modules and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc} ]]; then
    source ${ZIM_HOME}/zimfw.zsh init
fi

# Initialize modules.
source ${ZIM_HOME}/init.zsh

# zoxide
# export _ZO_DATA_DIR=$HOME/.local/share
export _ZO_ECHO=1
export _ZO_EXCLUDE_DIRS="$HOME:**/.git:**/.git/**:**/node_modules/**:/tmp:/tmp/**:/var/tmp/**"
if [ -n "$TMPDIR" ]; then
    _ZO_EXCLUDE_DIRS="$_ZO_EXCLUDE_DIRS:$TMPDIR:$TMPDIR/**"
fi
# eval "$(zoxide init --cmd cd zsh)"
eval "$(zoxide init --cmd z zsh)"

# bind keys
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# alias
# normally the zshrc is only loaded for interactive shell,
# but sometimes it is sourced manually so it is still worth
# to have the interactive shell check.
if [[ -o interactive ]]; then
  alias ls='eza --icons=auto'
  alias tree='eza --icons=auto --tree'
  alias grep='rg'
  alias cd='z'
fi

# my scripts
export PATH="$HOME/bin:$PATH"
# custom env
export PROJECTS_PATH=~/projects

claudecode() {
    # ANTHROPIC_BASE_URL="https://litellm.service.xianzzz.com" \
    # ANTHROPIC_AUTH_TOKEN="litellm" \
    # ANTHROPIC_SMALL_FAST_MODEL="gpt-mini" \
    # ANTHROPIC_BASE_URL="http://0.0.0.0:8787" \
    ANTHROPIC_BASE_URL="https://claude-router.service.xianzzz.com" \
    \claude --dangerously-skip-permissions "$@"
}

openaiapi(){
    OPENAI_API_KEY=$(op item get openai-api --vault dev --field credential --reveal) "$@"
}
