# Set the history file path
HISTFILE=$HOME/.zsh_history
# Set history save size and total history size
SAVEHIST=10000
HISTSIZE=10000
HISTORY_IGNORE="pwd:ls:clear"

# Set shell options for history behavior
setopt BANG_HIST
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
# Write the history file in the ':start:elapsed;command' format.
setopt EXTENDED_HISTORY

bindkey -v
export EDITOR=nvim

setopt PROMPT_SUBST

# Disallow `>` to overwrite existing files. Use `>|` or `>!` instead.
setopt NO_CLOBBER

# Allow comments starting with `#` in the interactive shell.
setopt INTERACTIVE_COMMENTS
# the cursor is moved to the end of the word if either a single match is inserted or menu completion is performed.
setopt alwaystoend

# Perform cd to a directory if the typed command is invalid, but is a directory.
setopt autocd
# useful for pushd, pushd +N, popd, cd -N, dirs -v
setopt autopushd
setopt pushdignoredups
setopt pushdsilent
# `PUSHDMINUS` swapped the meaning of `cd +1` and `cd -1`, in favor of `cd -N` for choosing N+1 th item from the top.
setopt pushdminus

setopt longlistjobs

# Ensures that Unicode combining characters are handled properly in Zsh
setopt combiningchars
# Allow completion in the middle of a word
setopt completeinword
# Disable XON/XOFF which is useless nowadays
# same as stty -ixon ?
setopt noflowcontrol

# ZSH uses this to determine how long to wait (in hundredths of a second) for additional characters in sequence. Default is 0.4 seconds.
# 1=10ms for key sequences
KEYTIMEOUT=1

#
# DOTFILES
#
if [[ -f "$HOME/dotfiles/config.yaml" ]]; then
  export DOTDROP_CONFIG="$HOME/dotfiles/config.yaml"
elif [[ -f "$HOME/projects/dotfiles/config.yaml" ]]; then
  export DOTDROP_CONFIG="$HOME/projects/dotfiles/config.yaml"
fi

#
# PLUGINS
#

# ohmyzsh vi mode
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=false
VI_MODE_SET_CURSOR=true
MODE_INDICATOR=""
INSERT_MODE_INDICATOR=""
VI_MODE_CURSOR_NORMAL=2
VI_MODE_CURSOR_VISUAL=0
VI_MODE_CURSOR_INSERT=6
VI_MODE_CURSOR_OPPEND=0

ZSH_PLUGIN_DIR=~/.zsh-plugins
ZIM_HOME=$ZSH_PLUGIN_DIR
ZIM_CONFIG_FILE=~/.zimrc

zstyle ':zim:zmodule' use 'degit'

# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
      https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

# Install missing modules and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc} ]]; then
  source ${ZIM_HOME}/zimfw.zsh init
fi

# Initialize modules.
source ${ZIM_HOME}/init.zsh

# apply theme after vi-mode to overwrite conflicts
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
  eval "$(oh-my-posh init zsh --config ${HOME}/.zsh-plugins/oh-my-posh-themes/custom.omp.toml)"
fi
