# Set the history file path
HISTFILE=$HOME/.zsh_history
# Set history save size and total history size
SAVEHIST=10000
HISTSIZE=10000
HISTORY_IGNORE="pwd:ls:clear"

# Set shell options for history behavior
setopt BANG_HIST
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
# Write the history file in the ':start:elapsed;command' format.
setopt EXTENDED_HISTORY

setopt PROMPT_SUBST

# Disallow `>` to overwrite existing files. Use `>|`(sh compatible) or `>!`(zsh only) instead.
setopt NO_CLOBBER

# Allow comments starting with `#` in the interactive shell.
setopt INTERACTIVE_COMMENTS
# the cursor is moved to the end of the word if either a single match is inserted or menu completion is performed.
setopt alwaystoend

# Perform cd to a directory if the typed command is invalid, but is a directory.
setopt autocd
# useful for pushd, pushd +N, popd, cd -N, dirs -v
setopt autopushd
setopt pushdignoredups
setopt pushdsilent
# `PUSHDMINUS` swapped the meaning of `cd +1` and `cd -1`, in favor of `cd -N` for choosing N+1 th item from the top.
setopt pushdminus

setopt longlistjobs

# Ensures that Unicode combining characters are handled properly in Zsh
setopt combiningchars
# Allow completion in the middle of a word
setopt completeinword
# Disable XON/XOFF which is useless nowadays
# same as stty -ixon ?
setopt noflowcontrol

# ZSH uses this to determine how long to wait (in hundredths of a second) for additional characters in sequence. Default is 0.4 seconds.
# 1=10ms for key sequences
KEYTIMEOUT=1

#
# DOTFILES
#
if [ -f "$HOME/dotfiles/config.yaml" ]; then
    export DOTDROP_CONFIG="$HOME/dotfiles/config.yaml"
elif [ -f "$HOME/projects/dotfiles/config.yaml" ]; then
    export DOTDROP_CONFIG="$HOME/projects/dotfiles/config.yaml"
fi

#
# PLUGINS
#
# zimfw
ZSH_PLUGIN_DIR=~/.zsh-plugins
ZIM_HOME=$ZSH_PLUGIN_DIR
ZIM_CONFIG_FILE=~/.config/zsh/.zimrc

zstyle ':zim:zmodule' use 'degit'

# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
    curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

# Install missing modules and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc} ]]; then
    source ${ZIM_HOME}/zimfw.zsh init
fi

# Initialize modules.
source ${ZIM_HOME}/init.zsh

if [[ -o interactive ]]; then
    _zimfw_autocheck() {
        (( ${+functions[zimfw]} )) || return

        zmodload zsh/datetime 2>/dev/null

        local stamp="${ZIM_HOME}/.zimfw-last-check"
        local now
        if [[ -n ${EPOCHSECONDS-} ]]; then
            now=$EPOCHSECONDS
        else
            now=$(date +%s)
        fi
        local ttl=$((7 * 24 * 60 * 60))

        if [[ -f ${stamp} ]]; then
            local last
            read -r last < "${stamp}"
            [[ -n ${last} ]] && (( now - last < ttl )) && return
        fi

        local output check_status show_msg=0 check_msg='[zimfw] Checking for updates...'
        if [[ -t 1 ]]; then
            printf '%s' "${check_msg}"
            show_msg=1
        fi

        output=$(zimfw check)
        check_status=$?

        if (( show_msg )); then
            printf '\r%*s\r' ${#check_msg} ''
        fi

        if (( check_status == 0 )); then
            if [[ -n ${output} ]]; then
                printf '%s\n' "${output}"
                printf '%s\n' "[zimfw] Updates available. Run 'zimfw update' to apply."
            fi
            printf '%s\n' "${now}" >| "${stamp}"
        fi
    }

    _zimfw_autocheck
fi

#
# Vim Mode
#
bindkey -v
export EDITOR=nvim
export SYSTEMD_EDITOR=nvim

# change cursor
_fix_cursor() {
    local keymap=${1:-$KEYMAP}
    local shape=0
    case ${keymap} in
        vicmd|visual) shape=1 ;; # block
        viins|main|command|isearch) shape=5 ;; # beam
        viopp) shape=0 ;; # block
        *) shape=0 ;; # block
    esac
    printf $'\e[%d q' "${shape}"
}

__cursor_keymap_select() {
    _fix_cursor "${KEYMAP}"
}

__cursor_line_init() {
    _fix_cursor "${KEYMAP}"
}

__cursor_line_finish() {
    _fix_cursor vicmd
}

autoload -Uz add-zle-hook-widget

if (( ${+widgets[zle-keymap-select]} )); then
    add-zle-hook-widget keymap-select __cursor_keymap_select
else
    zle -N zle-keymap-select __cursor_keymap_select
fi

if (( ${+widgets[zle-line-init]} )); then
    add-zle-hook-widget line-init __cursor_line_init
else
    zle -N zle-line-init __cursor_line_init
fi

if (( ${+widgets[zle-line-finish]} )); then
    add-zle-hook-widget line-finish __cursor_line_finish
else
    zle -N zle-line-finish __cursor_line_finish
fi

#
# Theme
#
# if use ohmyzsh vi mode then this need to be placed after it to enable transient prompt
if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
    eval "$(oh-my-posh init zsh --config ${HOME}/.config/oh-my-posh/custom.omp.toml)"
fi

# fzf-tab config
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences (like '%F{red}%d%f') here, fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
# custom fzf flags
# NOTE: fzf-tab does not follow FZF_DEFAULT_OPTS by default
zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind=tab:accept
# To make fzf-tab follow FZF_DEFAULT_OPTS.
# NOTE: This may lead to unexpected behavior since some flags break this plugin. See Aloxaf/fzf-tab#455.
zstyle ':fzf-tab:*' use-fzf-default-opts yes
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

# ohmyzsh vi mode
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=false
VI_MODE_SET_CURSOR=true
MODE_INDICATOR=""
INSERT_MODE_INDICATOR=""
VI_MODE_CURSOR_NORMAL=1
VI_MODE_CURSOR_VISUAL=1
VI_MODE_CURSOR_INSERT=5
VI_MODE_CURSOR_OPPEND=0

# zsh-autosuggestions
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# zsh-syntax-highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS+=(main brackets pattern)
typeset -A ZSH_HIGHLIGHT_PATTERNS
# To have commands starting with `rm -rf` highlighted:
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=yellow,bold,underline')

# fd
# see also fd ignore file in ~/.config/fd/ignore
alias fd='fd --hidden --exclude .git' #-p

# fzf
# fzf, use fd instead of find (fd reads ~/.fdignore)
# Always wrap: bat wraps to preview width; fzf preview pane also wraps as backup.
local _fzf_preview_argument="if [ -d {} ]; \
  then eza -a --tree -L1 --color=always --icons=always {} | head -n 200; \
  else bat --color=always --wrap=auto --terminal-width=\${FZF_PREVIEW_COLUMNS:-\${COLUMNS}} --line-range=:500 {}; \
  fi"
export FZF_DEFAULT_COMMAND="fd -H -E .git --type d --type f"
# Ctrl + T command
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
# Alt + C command 
export FZF_ALT_C_COMMAND="fd -H -E .git --type d"
export FZF_CTRL_T_OPTS="--bind 'ctrl-/:toggle-preview' ${FZF_CTRL_T_OPTS:-} --preview '${_fzf_preview_argument}' --preview-window wrap"
export FZF_ALT_C_OPTS="--bind 'ctrl-/:toggle-preview' ${FZF_ALT_C_OPTS:-} --preview '${_fzf_preview_argument}' --preview-window wrap"
# allow color from fd and set sane preview defaults globally
export FZF_DEFAULT_OPTS="--ansi ${FZF_DEFAULT_OPTS:-}"
# "**" command syntax
_fzf_compgen_path() {
    fd -H -E .git --type d --type f . "$1"
}
# "**" command syntax (for directories only)
_fzf_compgen_dir() {
    fd -H -E .git --type d . "$1"
}
_fzf_comprun() {
    local command=$1
    shift

    case "$command" in
        export|unset) fzf --preview "eval 'echo \$'{}" "$@" ;;
        ssh) fzf --preview "dig {}" "$@" ;;
        *) fzf --preview "${_fzf_preview_argument}" --preview-window wrap "$@" ;;
    esac
}
alias fzfp="fzf --preview '${_fzf_preview_argument}' --preview-window wrap"

source <(fzf --zsh)

# zoxide
# export _ZO_DATA_DIR=$HOME/.local/share
export _ZO_ECHO=1
export _ZO_EXCLUDE_DIRS="$HOME:**/.git:**/.git/**:**/node_modules/**:/tmp:/tmp/**:/var/tmp/**"
if [ -n "$TMPDIR" ]; then
    _ZO_EXCLUDE_DIRS="$_ZO_EXCLUDE_DIRS:$TMPDIR:$TMPDIR/**"
fi
# eval "$(zoxide init --cmd cd zsh)"
eval "$(zoxide init --cmd z zsh)"

# bind keys
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
autoload -Uz edit-command-line
zle -N edit-command-line
zle -A edit-command-line __cursor_edit_command_line_orig
__cursor_edit_command_line() {
    zle __cursor_edit_command_line_orig "$@"
    local ret=$?
    _fix_cursor "${KEYMAP:-viins}"
    return ${ret}
}
zle -N edit-command-line __cursor_edit_command_line
bindkey '^X^E' edit-command-line

# alias
# normally the zshrc is only loaded for interactive shell,
# but sometimes it is sourced manually so it is still worth
# to have the interactive shell check.
if [[ -o interactive ]]; then
  alias ls='eza --icons=auto'
  alias tree='eza --icons=auto --tree'
  alias grep='rg'
  alias cd='z'
fi

# custom env
export PROJECTS_PATH=~/projects

claudecode() {
    # ANTHROPIC_BASE_URL="https://litellm.service.xianzzz.com" \
    # ANTHROPIC_AUTH_TOKEN="litellm" \
    # ANTHROPIC_SMALL_FAST_MODEL="gpt-mini" \
    # ANTHROPIC_BASE_URL="http://0.0.0.0:8787" \
    ANTHROPIC_BASE_URL="https://claude-router.service.xianzzz.com" \
    \claude --dangerously-skip-permissions "$@"
}

openaiapi(){
    OPENAI_API_KEY=$(op item get openai-api --vault dev --field credential --reveal) "$@"
}
