[preferred]
default=gnome;gtk;kde;
org.freedesktop.impl.portal.Access=gtk;
org.freedesktop.impl.portal.Notification=gtk;
org.freedesktop.impl.portal.Secret=kwallet;gnome-keyring;
# prefer GNOME settings integration for GTK apps in Niri
org.freedesktop.impl.portal.Settings=gnome;gtk;kde;
org.freedesktop.impl.portal.FileChooser=gnome;gtk;kde;
