[preferred]
default=gnome;gtk;kde;
org.freedesktop.impl.portal.Access=gtk;
org.freedesktop.impl.portal.Notification=gtk;
org.freedesktop.impl.portal.Secret=kwallet;gnome-keyring;
# prefer plasma for theme settings
org.freedesktop.impl.portal.Settings=kde;gnome;gtk;
org.freedesktop.impl.portal.FileChooser=kde;gnome;gtk;
