[preferred]
default=gnome;gtk;wlr;kde;
org.freedesktop.impl.portal.Access=gtk;
org.freedesktop.impl.portal.Notification=gtk;
org.freedesktop.impl.portal.Secret=kwallet;
org.freedesktop.impl.portal.Settings=gnome;gtk;kde;
org.freedesktop.impl.portal.FileChooser=gnome;gtk;kde;
