[preferred]
default=gtk;gnome;wlr;kde;
org.freedesktop.impl.portal.Access=gtk;
org.freedesktop.impl.portal.Notification=gtk;
org.freedesktop.impl.portal.Secret=kwallet;gnome-keyring;
org.freedesktop.impl.portal.Settings=gnome;gtk;kde;
org.freedesktop.impl.portal.FileChooser=gtk;gnome;kde;
