config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  impignore: &global_ignore
  - '*.log'
  - '*.DS_Store'
  cmpignore: *global_ignore
  upignore: *global_ignore
  instignore: *global_ignore
dotfiles:
  f_etc_keyd_default.conf:
    src: etc/keyd/default.conf
    dst: /etc/keyd/default.conf
    actions:
    - install keyd
  d_config_ibus_rime:
    src: config/ibus/rime
    dst: ~/.config/ibus/rime
    cmpignore:
    - '*'
    - '!/!(sync)/*.custom.yaml'
    upignore:
    - '*'
    - '!/!(sync)/*.custom.yaml'
    chmod: '700'
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    actions:
    - install fzf
    - install zoxide
    - install bat
    - install fd
    - install eza
  f_etc_fonts_local.conf:
    src: etc/fonts/local.conf
    dst: /etc/fonts/local.conf
  d_config_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    actions:
    - install neovim
    cmpignore: &nvim_ignore
    - '*lock.json'
    upignore: *nvim_ignore
  d_config_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    chmod: '700'
  d_config_oh-my-posh:
    src: config/oh-my-posh
    dst: ~/.config/oh-my-posh
  d_config_wezterm:
    src: config/wezterm
    dst: ~/.config/wezterm
  d_bin:
    src: bin
    dst: ~/bin
  d_config_sunshine:
    src: config/sunshine
    dst: ~/.config/sunshine
    cmpignore: &sunshine_ignore
    - '*/credentials/*'
    - '*state.json'
    upignore: *sunshine_ignore
  d_etc_sddm.conf.d:
    src: etc/sddm.conf.d
    dst: /etc/sddm.conf.d
  f_etc_mkinitcpio.conf:
    src: etc/mkinitcpio.conf
    dst: /etc/mkinitcpio.conf
  d_config_fcitx5_conf:
    src: config/fcitx5/conf
    dst: ~/.config/fcitx5/conf
    chmod: '700'
    cmpignore: &fcitx_ignore
    - cached_layouts
    upignore: *fcitx_ignore
  f_config_kglobalshortcutsrc:
    src: config/kglobalshortcutsrc
    dst: ~/.config/kglobalshortcutsrc
    chmod: '600'
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    chmod: '600'
  d_config_1password_ssh:
    src: config/1Password/ssh
    dst: ~/.config/1Password/ssh
    chmod: '700'
  d_config_systemd_user_sunshine.service.d:
    src: config/systemd/user/sunshine.service.d
    dst: ~/.config/systemd/user/sunshine.service.d
  d_ssh:
    src: ssh
    dst: ~/.ssh
    chmod: '700'
    template: false
    cmpignore: &ssh_ignore
    - known_hosts*
    # the config is a template file and should have a separate entry 
    # to avoid being overwritten during update
    - config
    upignore: *ssh_ignore
    instignore: *ssh_ignore
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  f_etc_makepkg.conf:
    src: etc/makepkg.conf
    dst: /etc/makepkg.conf
  d_config_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
    actions:
    - install alacritty
  d_config_tmux:
    src: config/tmux
    dst: ~/.config/tmux
    actions:
    - install tmux
  d_config_fd:
    src: config/fd
    dst: ~/.config/fd
  d_config_autostart:
    src: config/autostart
    dst: ~/.config/autostart
  d_etc_docker:
    src: etc/docker
    dst: /etc/docker
profiles:
  base:
    dotfiles:
    - d_config_nvim
    - f_gitconfig
    - d_ssh
    - f_ssh_config
    - d_config_1password_ssh
    - d_config_alacritty
  posix_base:
    include:
    - base
    dotfiles:
    #- d_config_wezterm
    - f_zshrc
    - d_config_zsh
    - d_config_oh-my-posh
    - d_config_tmux
    - d_config_fd
  posix_utils:
    dotfiles:
    - d_bin
  os_linux:
    include:
    - posix_base
    - posix_utils
    dotfiles:
    - f_etc_keyd_default.conf
    - d_etc_docker
  os_arch:
    variables:
      install_cmd: yay -S --needed --answerdiff=None --answeredit=None --removemake
        {0}
    include:
    - os_linux
    dotfiles:
    - f_etc_makepkg.conf
    - f_etc_fonts_local.conf
  os_arch_kernel:
    dotfiles:
    - f_etc_mkinitcpio.conf
  de_gnome:
    dotfiles:
    - d_config_ibus_rime
    - d_config_autostart
  de_kde:
    dotfiles:
    - d_etc_sddm.conf.d
    - f_config_kglobalshortcutsrc
    - d_config_fcitx5_conf
  os_mac:
    variables:
      install_cmd: brew install --quiet {0}
    include:
    - posix_base
  xian-linux-server:
    include:
    - os_arch
    - de_gnome
    dotfiles:
    - d_config_sunshine
    - d_config_systemd_user_sunshine.service.d
  aegis.lan:
    include:
    - os_mac
variables:
  install_cmd: echo 'no install cmd for {0} >&2'
actions:
  install: '{{@@ install_cmd @@}}'
