config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
dotfiles:
  f_etc_keyd_default.conf:
    src: etc/keyd/default.conf
    dst: /etc/keyd/default.conf
  f_config_ibus_rime_default.custom.yaml:
    src: config/ibus/rime/default.custom.yaml
    dst: ~/.config/ibus/rime/default.custom.yaml
  f_config_ibus_rime_ibus_rime.custom.yaml:
    src: config/ibus/rime/ibus_rime.custom.yaml
    dst: ~/.config/ibus/rime/ibus_rime.custom.yaml
  f_config_ibus_rime_rime_ice.custom.yaml:
    src: config/ibus/rime/rime_ice.custom.yaml
    dst: ~/.config/ibus/rime/rime_ice.custom.yaml
  f_config_1password_ssh_agent.toml:
    src: config/1Password/ssh/agent.toml
    dst: ~/.config/1Password/ssh/agent.toml
    chmod: '600'
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zimrc:
    src: zimrc
    dst: ~/.zimrc
  d_zsh-plugins_oh-my-posh-themes:
    src: zsh-plugins/oh-my-posh-themes
    dst: ~/.zsh-plugins/oh-my-posh-themes
  f_etc_fonts_local.conf:
    src: etc/fonts/local.conf
    dst: /etc/fonts/local.conf
profiles:
  xian-linux-server:
    dotfiles:
    - f_etc_keyd_default.conf
    - f_config_ibus_rime_default.custom.yaml
    - f_config_ibus_rime_ibus_rime.custom.yaml
    - f_config_ibus_rime_rime_ice.custom.yaml
    - f_config_1password_ssh_agent.toml
    - f_zshrc
    - f_zimrc
    - d_zsh-plugins_oh-my-posh-themes
    - f_etc_fonts_local.conf
