[ignore]
pull = [
    "*.dotdropbak",
    "*.bak",
    "__pycache__/",
]
push = [
    "*.archived",
    "*.bak",
    "__pycache__/",
]

[hooks]
guard_push = [
    'sh "$DOTMAN_REPO_ROOT/scripts/check_core_env.sh"',
]
