address_family = both
ds5_inputtino_randomize_mac = disabled
global_prep_cmd = [{"do":"sh -c \"${XDG_CONFIG_HOME:-$HOME/.config}/sunshine/sunshine-prep-niri.py do --width ${SUNSHINE_CLIENT_WIDTH} --height ${SUNSHINE_CLIENT_HEIGHT} --fps ${SUNSHINE_CLIENT_FPS} --solo --scale auto --inhibit\"","undo":"sh -c \"${XDG_CONFIG_HOME:-$HOME/.config}/sunshine/sunshine-prep-niri.py undo\""}]
capture = kms
lan_encryption_mode = 1
stream_audio = true
