address_family = both
global_prep_cmd = [{"do":"sh -c \"${XDG_CONFIG_HOME:-$HOME/.config}/sunshine/sunshine-prep-kde.py do --width ${SUNSHINE_CLIENT_WIDTH} --height ${SUNSHINE_CLIENT_HEIGHT} --fps ${SUNSHINE_CLIENT_FPS}\"","undo":"sh -c \"${XDG_CONFIG_HOME:-$HOME/.config}/sunshine/sunshine-prep-kde.py undo\""}]

