onboarding = false

[keys]
switch_workspace = "ctrl+1..9"
previous_workspace = "ctrl+shift+k"
next_workspace = "ctrl+shift+j"
previous_agent = "ctrl+shift+h"
next_agent = "ctrl+shift+l"

[[keys.command]]
key = "prefix+\\"
type = "shell"
command = "$HOME/.local/libexec/herdr/reviewr-focus-toggle"
description = "Toggle reviewr and focus it when opened"

[theme]
name = "gruvbox"
auto_switch = false

[theme.custom]
surface_dim = "#504945"

[ui]
show_agent_labels_on_pane_borders = false
mouse_scroll_lines = 1

[experimental]
pane_history = true

[ui.toast]
delivery = "off"

[ui.sound]
enabled = false
