include themes/gruvbox-everforest.conf

# Window
initial_window_width 100c
initial_window_height 25c
window_padding_width 0
dynamic_padding yes
background_opacity 0.9

# Tab bar
# Keep Kitty's default tab titles; avoid default fade "shade ladder" tab style.
tab_bar_style separator
tab_separator " │ "
tab_bar_background #282828
active_tab_foreground #282828
active_tab_background #d8a657
inactive_tab_foreground #d4be98
inactive_tab_background #3c3836

# Font
font_family CaskaydiaCove Nerd Font Mono
font_size 19.0

# Cursor
cursor_shape block
cursor_blink_interval 0
# cursor_trail 1

# Tabs
map kitty_mod+h previous_tab
map kitty_mod+l next_tab

# Clipboard
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
map shift+delete combine : copy_to_clipboard : clear_selection
# tmux does not support full kitty keyboard protocol but a subset in csi-u
# so kitty is conservative on modifier+enter
# we need to explicitly enable csi-u format for enter in tmux
map shift+enter send_text all \x1b[13;2u
