[Unit]
; After=graphical-session.target
; After=xdg-desktop-autostart.target
After=graphical.target systemd-logind.service
# pull in required if havent, logind for device accesses.
Wants=graphical.target systemd-logind.service
[Service]
StandardOutput=null
StandardError=null
[Install]
; WantedBy=graphical-selssion.target
WatedBy=default.target
