include themes/gruvbox-everforest.conf

# Window
initial_window_width 100c
initial_window_height 25c
window_padding_width 0
dynamic_padding yes
background_opacity 0.9

# Font
font_family CaskaydiaCove Nerd Font Mono
font_size 19.0

# Cursor
cursor_shape block
cursor_blink_interval 0
# cursor_trail 1

# Clipboard
map ctrl+insert copy_to_clipboard
