includes = ["runtime/linux"]

[vars]
INSTALL = "sh \"$DOTMAN_REPO_ROOT/scripts/install_arch_packages.sh\""
PROBE_PACKAGES_INSTALLED = "sh \"$DOTMAN_REPO_ROOT/scripts/probe_arch_packages_installed.sh\""
INSTALL_CUSTOM_PACKAGE = "sh \"$DOTMAN_REPO_ROOT/scripts/install_arch_custom_package.sh\""
NODEJS_INSTALL_PACKAGES = "nodejs npm"
