#set -s default-terminal "tmux-256color"

unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded"

set -g prefix C-b
set -g prefix2 `
bind ` send `

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key = split-window -h
bind-key - split-window -v

#bind-key \\ last-window

bind \' switch-client -t'{marked}'

bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# hori
bind H choose-window 'join-pane -h -s "%%"'
# verti
bind J choose-window 'join-pane -s "%%"'
