[Unit]
# Ensure Sunshine starts after the graphical session (Wayland/Hyprland)
After=graphical-session.target
PartOf=graphical-session.target
# After=xdg-desktop-autostart.target

[Service]
# StandardOutput=null
# StandardError=null
# This can reset the previously set ExecStartPre
ExecStartPre=
ExecStartPre=ydotool mousemove -x 1 -y 1

[Install]
WantedBy=graphical-session.target
