[general]
import = ["~/.config/alacritty/themes/gruvbox_everforest_dark.toml"]

[window]
dimensions = { columns = 100, lines = 25 }

padding = { x = 0, y = 0 }

dynamic_padding = true
#decorations = "Buttonless"
opacity = 0.9

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
size = 19

[colors]
# rose gold = '#F1C2A6'
cursor = { cursor = "#F1C2A6" }
vi_mode_cursor = { text = "CellBackground", cursor = "#F1C2A6" }
selection = { text = "CellBackground", cursor = "#F1C2A6" }

[cursor]
vi_mode_style = { shape = "Block", blinking = "Off" }

[terminal]
osc52 = "OnlyCopy"

[[keyboard.bindings]]
key = "Insert"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"

[[keyboard.bindings]]
key = "Delete"
mods = "Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Delete"
mods = "Shift"
action = "ClearSelection"

# shift+enter in tmux session
# tmux does not fully support kitty keyboard protocol
# need to explicit send the csi-u seq for shift+enter in tmux
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
# \u001b = \x1b but toml does not allow escaping \x...
chars = "\u001b[13;2u"

