approval_policy = "on-request"
sandbox_mode = "workspace-write"
model_reasoning_effort = "medium"
web_search = "live"
model = "gpt-5.4"
personality = "pragmatic"

[profiles.obsidian]
model = "gpt-5.1-codex-mini"
model_reasoning_effort = "medium"
approval_policy = "on-request"

# Extra settings that only apply when `sandbox = "workspace-write"`.
[sandbox_workspace_write]
# Allow the command being run inside the sandbox to make outbound network
# requests. Disabled by default.
network_access = true
writable_roots = ["~/.local/share/Trash"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[notice]
hide_full_access_warning = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.3-codex"
"gpt-5.1-codex-mini" = "gpt-5.2-codex"

[features]
multi_agent = true

[tui]
status_line = ["model-with-reasoning", "current-dir", "git-branch", "context-remaining"]

# [mcp_servers.mcp-web-context]
# command = "uvx"
# args = ["mcp-proxy", "--transport", "streamablehttp", "https://scraper.service.xianzzz.com/mcp"]
