# NOTE: to use this, rename this file to default.conf and put it in /etc/keyd/

# Mac-Like Configuration

[ids]
# device ids
*

[global]
# chord_timeout = 100  # default 50ms, bump if needed

[aliases]

[main]
capslock = esc
# alt = layer(super_alt)
# Use the 'leftmeta' key as the new "Cmd" key, activating the 'meta_mac' layer
leftmeta = layer(meta_mac)
# leftmeta = overload(meta_mac,leftmeta)
# leftcontrol = layer(control_super)

# rightcontrol+leftmeta = leftmeta
rightcontrol = layer(control_capslock)

[super_alt:M]

[control_capslock:C]
leftmeta = meta

# issues:
# the ctrl+click for new tab does not work, bc meta+click is for moving windows
# need also add a lot of shift+ctrl mappings
[control_super:M]
leftcontrol = swap(meta)

` = C-`

z = C-z
x = C-x
c = C-insert
v = S-insert
b = C-b
/ = C-/

a = C-a
s = C-s
d = C-d
f = C-f

i = C-i
q = C-q
w = C-w
e = C-e
r = C-r
t = C-t
o = C-o
p = C-p
[ = C-[
] = C-]
\ = C-\

# input_switch
space = swapm(control, C-space)

# The 'meta_mac' modifier layer; inherits from the 'Ctrl' modifier layer
[meta_mac:C]
rightcontrol = swap(meta)

# show overview
esc = M-esc
space = M-space

# Switch directly to an open tab (e.g., Firefox, VS Code)
# 1 = A-1
# 2 = A-2
# 3 = A-3
# 4 = A-4
# 5 = A-5
# 6 = A-6
# 7 = A-7
# 8 = A-8
# 9 = A-9

# Copy
c = C-insert
#c = rightcontrol+c
# Paste
v = S-insert
# Cut
x = S-delete

# Move cursor to the beginning of the line
#left = home
# Move cursor to the end of the line
#right = end

# As soon as 'tab' is pressed (but not yet released), switch to the 'app_switch_state' overlay
# Send a 'M-tab' key tap before entering 'app_switch_state'
tab = swapm(app_switch, A-tab)

# Meta-Backtick: Switch to the next window in the application group
# Default binding for 'cycle-group' in GNOME
# ` = A-f6
` = swapm(app_switch, A-`)

[control]
#space = swapm(input_switch, M-space)

[control+alt]
enter = M-enter
backspace = M-backspace
up = M-up
down = M-down
left = M-left
right = M-right

[app_switch:A]

# 'app_switch_state' modifier layer; inherits from the 'Meta' modifier layer
# deprecated
[app_switch_meta_key:M]

# Meta-Tab: Switch to the next application
# tab = M-tab
right = M-tab

# Meta-Backtick: Switch to the previous application
` = M-S-tab
left = M-S-tab

[input_switch:M]
# space = M-space

[shift+meta_mac]
# for 1password, set this in system settings
space = S-C-M-space

# copy with shift
c = S-C-c
v = S-C-v
x = S-C-x

[shift+control_super]
# for 1password, set this in system settings
space = S-C-M-space

# copy with shift
c = S-C-c
v = S-C-v
x = S-C-x

[meta_mac+control]
d = macro(leftmouse 30ms leftmouse 80ms C-insert 100ms C-M-d)
# full screen
f = M-f
[control_super+control]
d = macro(leftmouse 30ms leftmouse 80ms C-insert 100ms C-M-d)
# full screen
f = M-f

[shift]
esc = swap(meta)
